### ISSUE TITLE
Default keybinding?

### ISSUE THREAD

**Issue by trusktr** [t9md/atom-vim-mode-plus-ex-mode#11]
Why not have a default keybinding with a checkbox to enable/disable?

**Comment by t9md** [comment]
I can't understand what is your point, sorry.

**Comment by trusktr** [comment]
I've added the keybinding, but the resolver shows nothing:

![screen shot 2016-06-10 at 5 52 04 pm](https://cloud.githubusercontent.com/assets/297678/15982187/3a0e2c84-2f36-11e6-87e7-da63df523c88.png)

Any ideas what to check?

**Comment by trusktr** [comment]
![screen shot 2016-06-10 at 5 52 04 pm](https://cloud.githubusercontent.com/assets/297678/15982187/3a0e2c84-2f36-11e6-87e7-da63df523c88.png)

**Comment by t9md** [comment]
Ah, got it for original your comment, yes I think I'm OK to provide default keybinding for `:`, will do in next release.

But for next question why your keymap not working is not sure, strange.
Both `:` and `!` not work?
Can you insert `:` and `!` without problem in `insert-mode`.
If so, when you type `:` in normal-mode, keymap resolver should say `vim-mode-plus-ex-mode:open`.

**Comment by trusktr** [comment]
> Both : and ! not work?

Yep, both not working.

> Can you insert : and ! without problem in insert-mode.

Yeah, that works fine.

> If so, when you type : in normal-mode, keymap resolver should say vim-mode-plus-ex-mode:open.

The resolver shows empty:

![screen shot 2016-06-12 at 11 36 04 am](https://cloud.githubusercontent.com/assets/297678/15993137/f10a80a2-3091-11e6-88af-6afec423163c.png)

**Comment by t9md** [comment]
This is same issue I explained you in vim-mode-plus's issue.
You need to understand Atom's keymap system. Not my issue.
Don't use same scope twice in `keymap.cson`.

**Comment by trusktr** [comment]
Ah, thanks. It works now. And now I know: cson is exactly like json (with alternate syntax). I have zero Coffee experience.

**Comment by t9md** [comment]
If so, you first read Atom's flight manual(in official page), I don't want to spend my time by explaining basic Atom concept, feature.
