### ISSUE TITLE
Updated to 0.5, now doesn't work

### ISSUE THREAD

**Issue by ghost** [t9md/atom-vim-mode-plus-ex-mode#13]
Prior to updating from Atom setting tab earlier this morning, I was able to do `:`, get the command pane thingy, then type `w` and save, or type `vsplit` and get vertical split. That's now not working at all after the upgrade.

Let me know if you need any additional info to debug.

**Comment by t9md** [comment]
- output of `atom --version`
- output of `apm list`
- Have you set `:` keybinding in your `keymap.cson`( I believe so since you can use before update).
- How about restarting atom, anything change?

**Comment by ghost** [comment]
OK, I feel dumb. 

I restarted it and it's now working. That's odd, because after the update, I could have sworn it prompted me to restart and I did. 

Anyways, sorry for the noise and thanks for the quick response. :)
