### ISSUE TITLE
esc then press ":" have no response

### ISSUE THREAD

**Issue by spellforce** [t9md/atom-vim-mode-plus-ex-mode#21]
[Check this](https://github.com/t9md/atom-vim-mode-plus/blob/master/ISSUE_TEMPLATE.md)

**Comment by sdwilsh** [comment]
Seeing this as well:
Atom    : 1.12.7
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
vim-mode-plus: 0.66.1
vim-mode-plus-ex-mode: 0.7.1

**Comment by FazleArefin** [comment]
I am getting the same issue - typing ':' has no response.

Atom    : 1.13.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
vim-mode-plus: 0.80.0
vim-mode-plus-ex-mode: 0.7.1

**Comment by t9md** [comment]
Give me precise steps which can reproduce this with high percentage?
Currently provided information is too small to make me think to start investigating.

**Comment by FazleArefin** [comment]
Steps to reproduce this on my system:

- (I have both vim-mode-plus and vim-mode-plus-ex-mode installed. Versions listed above. I do not have vim-mode or ex-mode installed)
- launch atom
- File > New File
- Press i to go to insert mode
- write something
- press ESC to get out of insert mode
- type :w (I was expecting the file to be save but nothing happens)

**Comment by t9md** [comment]
Thanks! will check!

**Comment by t9md** [comment]
Tried but failed to reproduce.

- Can you reproduce 100%? What OS are you using?
- Can you narrow down the condition this issue would happen? what keybinding-resolver saying when `:` was not show vmp-ex-mode dialog(reproduce issue by enabling keybinding-resolver via `cmd-.` then repro/observe the reaction for the keystroke `:`).
- When `:` do nothing, can you still invoke `ex-mode:open` from command-palette?

I need answer for **ALL** the question above to understand issue correctly.

**Comment by dalehille** [comment]
- _Can you reproduce 100%? What OS are you using?_
**Yes, on macOS Sierra 10.12.2 for me**

- _Can you narrow down the condition this issue would happen? what keybinding-resolver saying when : was not show vmp-ex-mode dialog(reproduce issue by enabling keybinding-resolver via cmd-. then repro/observe the reaction for the keystroke :)._
![image](https://cloud.githubusercontent.com/assets/1749799/22060395/8fe297ec-dd3e-11e6-8158-3cfcc23657d6.png)

- _When : do nothing, can you still invoke ex-mode:open from command-palette?
**Yes**
![image](https://cloud.githubusercontent.com/assets/1749799/22060445/c471e026-dd3e-11e6-8445-ffdab1514bf2.png)

**Comment by FazleArefin** [comment]
- Can you reproduce 100%? What OS are you using?
Yes. Ubuntu GNOME 16.10

- Can you narrow down the condition this issue would happen? what keybinding-resolver saying when : was not show vmp-ex-mode dialog(reproduce issue by enabling keybinding-resolver via cmd-. then repro/observe the reaction for the keystroke :).
Same as the previous comment by @dalehille 
 
- When : do nothing, can you still invoke ex-mode:open from command-palette?
No

**Comment by aouaki** [comment]
Did you add the keymap ?
```
'atom-text-editor.vim-mode-plus.normal-mode':
  ':': 'vim-mode-plus-ex-mode:open'
  '!': 'vim-mode-plus-ex-mode:toggle-setting'
```

**Comment by dalehille** [comment]
Thanks @aouaki , that resolved it for me

**Comment by FazleArefin** [comment]
Thanks @aouaki . Fixed.

**Comment by FazleArefin** [comment]
@t9md I think the readme needs to be updated to provide a clearer instruction on adding the keymap. **Edit > Keymap**, then paste

```
'atom-text-editor.vim-mode-plus.normal-mode':
  ':': 'vim-mode-plus-ex-mode:open'
  '!': 'vim-mode-plus-ex-mode:toggle-setting'
```

**Comment by t9md** [comment]
Will provide **default keymaps** so that I and other new users no longer spend time for this issue.

**Comment by sdwilsh** [comment]
That'd be ideal :)

The ex-mode plugin for vim-mode did that, and that's why I thought it was broken in this one.

**Comment by t9md** [comment]
From v0.8.1 no longer need custom keymaps(v0.8.0 was unpublished in 5min after release, just was mistake).

**Comment by t9md** [comment]
Thanks @dalehille for your help.

**Comment by t9md** [comment]
Oh, I should say thanks to you @aouaki . sorry, above my comment was intended to do that, just mistake 😅
