### ISSUE TITLE
support to set nohl, no highlight

### ISSUE THREAD

**Issue by ajith92** [t9md/atom-vim-mode-plus-ex-mode#22]
It is important to turn off the highlighting when it is not required any more

**Comment by t9md** [comment]
I wont directly mimic original ex-mode command.
- [already supported] For `set nohl`, use `vim-mode-plus-ex-mode:toggle-setting` then choose `Highlight Search`.
- [will implement] For `nohl` there is already corresponding vim-mode-plus command, so supporting it in this package is easy.

**Comment by t9md** [comment]
released v0.9.0.
