### ISSUE TITLE
:wq triggers Atom's "'filename' has changes, do you want to save them?" message

### ISSUE THREAD

**Issue by justinjhendrick** [t9md/atom-vim-mode-plus-ex-mode#23]
Repro:
1) edit a file
2) :wq

Expected:
file is saved, tab is closed

Actual:
Atom dialog box with "'filename' has changes, do you want to save them?" and I have to choose save.

Info:
Atom version: 1.14.2 x64
vim-mode-plus version: 0.82.3
vim-mode-plus-ex-mode version: 0.9.0

**Comment by justinjhendrick** [comment]
Works now. It was an atom change that fixed it, I guess.

Info:
Atom version: 1.15.9 x64
vim-mode-plus version: 0.82.3
vim-mode-plus-ex-mode version: 0.9.0

**Comment by t9md** [comment]
Thanks for reporting, I myself haven't seen this issue.
But I now have info upgrading Atom solve problem.
