### ISSUE TITLE
substitute

### ISSUE THREAD

**Issue by ae0000** [t9md/atom-vim-mode-plus-ex-mode#5]
Would it be possible to take :s/foo/bar/g and add that to the built in atom find/replace, then click submit?

If anything was currently selected, it would select the "Only in selection" option. 

I'd be willing to have a crack at it, but I haven't touched any atom code before - would be great to know if its even possible...?

**Comment by t9md** [comment]
I don't want to support it. You have two option.
- Use native find-and-replace package feature(I recommend)
- ask [ex-mode](https://github.com/lloeki/ex-mode)'s author to support vim-mode-plus and switch to use it from this package.

**Comment by RootlessAgrarian** [comment]
I'm going to risk public chastisement and say ditto, I really want s/foo/bar/g -- muscle memory after 40 years of vim is very strong.  if anyone has a patch for vim-mode-plus that implements ex style substitute I'd be really happy to hear about it.
