### ISSUE TITLE
ex-mode not working?

### ISSUE THREAD

**Issue by psifertex** [t9md/atom-vim-mode-plus-ex-mode#7]
Am I missing something? I have installed both vim-mode-plus as well as vim-mode-plus-ex-mode but I can't use `:` to enter ex-mode. Is there anything I need to do? Both plugins show as installed.

**Comment by t9md** [comment]
Not providing default keymap see README.md.

I think I should provide default keymap `:`, will come later version.

**Comment by psifertex** [comment]
Sorry for missing that -- thanks for the update.
